#Application URL
url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

#Browser configuration
browser = firefox

#Valid Credentials
validusername = admin
validpassword = admin123

#InValid Credentials
invalidusername = admi
invalidpassword = admin

#Implicitwait
implicitwait = 10

#Explicitwait
explicitwait = 20